version: '3.8'

services:
  app:
    build: .
    container_name: my-app
    volumes:
      - .:/app
    networks:
      - my-network
    command: ./run_tests.sh

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - "4444:4444"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
